on:
  pull_request:
    branches: [ 'master' ]
    types: [ opened, reopened ]

jobs:
  check_pr_title_job:
    runs-on: ubuntu-latest
    steps:
      - name: Local action requires checking out the repo
        uses: actions/checkout@v4
      - name: Now perform the job's core action
        uses: ./.github/actions/check-pr-title
