on:
  pull_request:
    branches: [ 'master' ]
    types: [ opened, reopened ]

jobs:
  check_pr_title_job:
    runs-on: ubuntu-latest
    steps:
      - uses: sanjay-sridharan-personal/happy-birthday@master
