on:
  pull_request:
    branches: [ 'master' ]
    types: [ opened, reopened ]

jobs:
  check_pr_title_job:
    runs-on: ubuntu-latest
    steps:
      - id: check-pr-title
        uses: sanjay-sridharan-personal/javascript@master
