on: [push]

jobs:
  commit_message_convention:
    runs-on: ubuntu-latest
    steps:
      - name: Checks if commit message is compliant
        uses: sanjay-sridharan-personal/javascript@23fb7c4ac570abf79f73299abcc13776c385d233
