on:
  pull_request:
    branches: [ 'interview' ]
    types: [ opened ]

jobs:
  add_pr_label_job:
    runs-on: ubuntu-latest
    steps:
      - id: add-needs-review-label
        uses: sanjay-sridharan-personal/javascript@master
