on:
  pull_request:
    branches: [ 'master' ]
    types: [ opened ]

jobs:
  add_pr_label_job:
    runs-on: ubuntu-latest
    steps:
      - id: add-pr-label
        uses: sanjay-sridharan-personal/javascript@8406062fa28b8e5b4f5c8eae0b508ccb898ae244
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
