on:
  pull_request:
    branches: [ 'master' ]
    types: [ opened, reopened ]

jobs:
  check_pr_title_job:
    runs-on: ubuntu-latest
    steps:
      - id: Use local check-pr-title action
        uses: ./.github/actions/check-pr-title
