on:
  pull_request:
    branches: [ 'master' ]
    types: [ opened ]

jobs:
  add_pr_label_job:
    runs-on: ubuntu-latest
    steps:
      - id: add-pr-label
        uses: sanjay-sridharan-personal/javascript@3e778a27aead7a338c6000c4dfa6f26478b9c9aa
