on:
  pull_request:
    branches: [ 'interview' ]
    types: [ opened, reopened ]

jobs:
  add_pr_label_job:
    runs-on: ubuntu-latest
    steps:
      - id: add-pr-label
        uses: sanjay-sridharan-personal/javascript@interview
        with:
          whodaboss: ${{ secrets.whodaboss }}
